package com.java.nbu.hotels.service;

import com.java.nbu.hotels.entities.RoomEntity;
import com.java.nbu.hotels.repository.RoomRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Bean;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@Service
public class RoomService {
   // This means to get the bean called userRepository
   // Which is auto-generated by Spring, we will use it to handle the data
   //@Autowired(required = false)
   @Autowired
   @Qualifier("roomRepo")
   private RoomRepository repo;

   public List<RoomEntity> getRooms(){
      List<RoomEntity> rooms = new ArrayList();
      repo.findAll().forEach(roomEntity -> rooms.add(roomEntity));
      return rooms;
   }
}
